import { MetricsCards } from '@/components/dashboard/MetricsCards';
import { PageHeader } from '@/components/dashboard/PageHeader';
import { SectionCard } from '@/components/ui/SectionCard';
import { controlPlaneService } from '@/services/control-plane';

export default async function AnalyticsPage() {
  const analytics = await controlPlaneService.getAnalytics();

  return (
    <div className="space-y-6">
      <PageHeader title="Analytics" description="Measure tenant growth, tool usage, and platform intelligence KPIs for strategic decisions." />
      <MetricsCards items={analytics.kpis.map((kpi) => ({ label: kpi.label, value: kpi.value, delta: kpi.change, trend: 'up', description: 'Derived from analytics rollups and usage facts.' }))} />
      <div className="grid gap-6 xl:grid-cols-2">
        <SectionCard title="Tenant growth" description="Growth trend in activated tenants over recent periods.">
          <div className="space-y-3">
            {analytics.tenantGrowth.map((point) => (
              <div key={point.label}>
                <div className="mb-1 flex items-center justify-between text-sm text-slate-300"><span>{point.label}</span><span>{point.value}</span></div>
                <div className="h-3 rounded-full bg-white/5"><div className="h-3 rounded-full bg-cyan-400" style={{ width: `${point.value * 5}%` }} /></div>
              </div>
            ))}
          </div>
        </SectionCard>
        <SectionCard title="Tool usage by domain" description="Relative activity generated by domain-scoped tools.">
          <div className="space-y-3">
            {analytics.toolUsageByDomain.map((point) => (
              <div key={point.label}>
                <div className="mb-1 flex items-center justify-between text-sm text-slate-300"><span>{point.label}</span><span>{point.value.toLocaleString()}</span></div>
                <div className="h-3 rounded-full bg-white/5"><div className="h-3 rounded-full bg-violet-400" style={{ width: `${Math.min(100, point.value / 200)}%` }} /></div></div>
            ))}
          </div>
        </SectionCard>
      </div>
    </div>
  );
}
