import type { Permission } from '@/types/platform';

export const adminRoutePermissions = {
  overview: 'analytics:read',
  tenants: 'tenants:read',
  tenantMutations: 'tenants:write',
  apps: 'apps:read',
  appMutations: 'apps:write',
  users: 'users:read',
  userMutations: 'users:write',
  agents: 'agents:read',
  agentActions: 'agents:operate',
  tools: 'tools:read',
  models: 'models:read',
  modelSwitch: 'models:switch',
  memory: 'memory:read',
  knowledgeGraph: 'graph:read',
  events: 'events:read',
  eventStream: 'events:read',
  assistantChat: 'events:read',
  analytics: 'analytics:read',
  observability: 'observability:read',
  audit: 'audit:read',
  system: 'system:write',
} satisfies Record<string, Permission>;

export const protectedAdminRoutes = [
  { path: '/api/admin/overview', permission: adminRoutePermissions.overview },
  { path: '/api/admin/tenants', permission: adminRoutePermissions.tenants },
  { path: '/api/admin/tenants (POST)', permission: adminRoutePermissions.tenantMutations },
  { path: '/api/admin/tenants/[tenantId] (PATCH)', permission: adminRoutePermissions.tenantMutations },
  { path: '/api/admin/apps', permission: adminRoutePermissions.apps },
  { path: '/api/admin/apps (POST)', permission: adminRoutePermissions.appMutations },
  { path: '/api/admin/apps/[appId] (PATCH)', permission: adminRoutePermissions.appMutations },
  { path: '/api/admin/users', permission: adminRoutePermissions.users },
  { path: '/api/admin/users (POST)', permission: adminRoutePermissions.userMutations },
  { path: '/api/admin/users/[userId] (PATCH)', permission: adminRoutePermissions.userMutations },
  { path: '/api/admin/agents', permission: adminRoutePermissions.agents },
  { path: '/api/admin/agents/[agentId]/actions', permission: adminRoutePermissions.agentActions },
  { path: '/api/admin/tools', permission: adminRoutePermissions.tools },
  { path: '/api/admin/models', permission: adminRoutePermissions.models },
  { path: '/api/admin/models/switch', permission: adminRoutePermissions.modelSwitch },
  { path: '/api/admin/memory', permission: adminRoutePermissions.memory },
  { path: '/api/admin/knowledge-graph', permission: adminRoutePermissions.knowledgeGraph },
  { path: '/api/admin/events', permission: adminRoutePermissions.events },
  { path: '/api/admin/events/stream', permission: adminRoutePermissions.eventStream },
  { path: '/api/admin/assistant/chat', permission: adminRoutePermissions.assistantChat },
  { path: '/api/admin/analytics', permission: adminRoutePermissions.analytics },
  { path: '/api/admin/observability', permission: adminRoutePermissions.observability },
  { path: '/api/admin/audit', permission: adminRoutePermissions.audit },
  { path: '/api/admin/system', permission: adminRoutePermissions.system },
] as const;