import type { DashboardModuleDefinition } from '@/types/platform';

export const dashboardModules: DashboardModuleDefinition[] = [
  {
    slug: 'overview',
    title: 'Platform Overview',
    description: 'Executive overview of tenant scale, events, agents, service health, and queues.',
    pageLayout: 'Hero KPI strip, live incidents rail, model monitor, event stream, and orchestration health sections.',
    components: ['MetricsCards', 'EventStream', 'ModelMonitor'],
    apiEndpoints: ['/admin/overview', '/admin/events', '/admin/models', '/admin/observability'],
    databaseEntities: ['tenants', 'tenant_apps', 'events_outbox', 'audit_logs', 'agent_runs'],
    keyInteractions: ['Drill into incidents', 'Switch model views', 'Filter live events'],
  },
  {
    slug: 'tenants',
    title: 'Tenants',
    description: 'Tenant fleet management with plan, spend, quota, and health posture.',
    pageLayout: 'Summary cards above a sortable tenant management table with expansion drawers.',
    components: ['TenantManager', 'MetricsCards'],
    apiEndpoints: ['/admin/tenants'],
    databaseEntities: ['tenants', 'tenant_limits', 'tenant_billing', 'tenant_policies'],
    keyInteractions: ['Review quotas', 'Inspect regional health', 'Prepare onboarding or suspension actions'],
  },
  {
    slug: 'apps',
    title: 'Apps',
    description: 'All tenant applications across PWA, Flutter, admin, and API surfaces.',
    pageLayout: 'App registry table with runtime, region, environment, and agent attachment summaries.',
    components: ['MetricsCards'],
    apiEndpoints: ['/admin/apps'],
    databaseEntities: ['tenant_apps', 'deployments', 'release_channels'],
    keyInteractions: ['Track runtime footprint', 'Check environment status', 'Review agent attachment'],
  },
  {
    slug: 'users',
    title: 'Users',
    description: 'Cross-tenant administrative and app user management with RBAC visibility.',
    pageLayout: 'User directory with scoped role badges, last-seen activity, and account states.',
    components: ['MetricsCards'],
    apiEndpoints: ['/admin/users'],
    databaseEntities: ['users', 'profiles', 'roles', 'permissions', 'sessions'],
    keyInteractions: ['Audit role assignments', 'Inspect activity patterns', 'Support account operations'],
  },
  {
    slug: 'agents',
    title: 'Agents',
    description: 'Operational console for autonomous agents, tasks, decisions, and workflow versions.',
    pageLayout: 'Agent cards and operations grid with budgets, queues, logs, and control actions.',
    components: ['AgentMonitor', 'MetricsCards'],
    apiEndpoints: ['/admin/agents', '/admin/agents/{agentId}/actions'],
    databaseEntities: ['agents', 'agent_runs', 'agent_tasks', 'agent_decisions', 'agent_logs'],
    keyInteractions: ['Pause or restart agents', 'Change budgets', 'Update workflow version'],
  },
  {
    slug: 'tools',
    title: 'Tool Registry',
    description: 'Catalog of tool contracts with risk, schemas, permissions, and usage metrics.',
    pageLayout: 'Registry table with schema chips, permission badges, and usage telemetry columns.',
    components: ['ToolRegistryTable'],
    apiEndpoints: ['/admin/tools'],
    databaseEntities: ['tool_registry', 'tool_permissions', 'tool_audit_logs', 'tool_usage_rollups'],
    keyInteractions: ['Inspect schema contracts', 'Review risk posture', 'Track usage trends'],
  },
  {
    slug: 'models',
    title: 'AI Models',
    description: 'Planner, SQL, agent, and embedding model performance and switch controls.',
    pageLayout: 'Model cards with p95 latency, token burn, errors, and candidate switch controls.',
    components: ['ModelMonitor', 'MetricsCards'],
    apiEndpoints: ['/admin/models', '/admin/models/switch'],
    databaseEntities: ['model_registry', 'model_rollups', 'model_switch_audit'],
    keyInteractions: ['Compare active vs fallback models', 'Switch active models', 'Review token burn'],
  },
  {
    slug: 'memory',
    title: 'AI Memory',
    description: 'Memory scopes, compaction cadence, vector footprint, and retention posture.',
    pageLayout: 'Scoped memory tables with record counts and compaction history.',
    components: ['MetricsCards'],
    apiEndpoints: ['/admin/memory'],
    databaseEntities: ['ai_memory', 'memory_segments', 'embedding_jobs'],
    keyInteractions: ['Inspect memory density', 'Review compaction schedules', 'Monitor vector growth'],
  },
  {
    slug: 'knowledge-graph',
    title: 'Knowledge Graph',
    description: 'Interactive relationship exploration across users, vendors, listings, and agents.',
    pageLayout: 'Graph canvas with side filters, node inspector, and relation legend.',
    components: ['GraphExplorer'],
    apiEndpoints: ['/admin/knowledge-graph'],
    databaseEntities: ['graph_nodes', 'graph_edges', 'graph_snapshots', 'entity_embeddings'],
    keyInteractions: ['Filter node types', 'Inspect paths', 'Trace relationships'],
  },
  {
    slug: 'events',
    title: 'Events',
    description: 'Real-time stream of tenant, app, user, and agent generated events.',
    pageLayout: 'Filter bar above a live event stream with contextual payload summaries.',
    components: ['EventStream'],
    apiEndpoints: ['/admin/events'],
    databaseEntities: ['events_outbox', 'event_subscriptions', 'queue_messages'],
    keyInteractions: ['Filter by tenant', 'Filter by app', 'Filter by event type'],
  },
  {
    slug: 'analytics',
    title: 'Analytics',
    description: 'Platform intelligence, tenant growth, and tool usage analytics.',
    pageLayout: 'KPI cards, compact bar charts, and insight summaries.',
    components: ['MetricsCards'],
    apiEndpoints: ['/admin/analytics'],
    databaseEntities: ['analytics_rollups', 'usage_facts', 'insight_snapshots'],
    keyInteractions: ['Track growth trends', 'Compare domains', 'Review insight summaries'],
  },
  {
    slug: 'observability',
    title: 'Observability',
    description: 'Prometheus, Grafana, and Loki-backed health, backlog, and container status views.',
    pageLayout: 'Health cards plus service status table and observability integration panel.',
    components: ['MetricsCards'],
    apiEndpoints: ['/admin/observability'],
    databaseEntities: ['service_health_rollups', 'queue_metrics', 'log_archives'],
    keyInteractions: ['Inspect health posture', 'Track queue backlog', 'Jump to Grafana or Loki'],
  },
  {
    slug: 'audit',
    title: 'Audit Log',
    description: 'Compliance-ready trail of administrative changes, model switches, agent actions, and client errors.',
    pageLayout: 'Filterable audit log table with export actions and scope-aware history.',
    components: ['MetricsCards'],
    apiEndpoints: ['/admin/audit'],
    databaseEntities: ['audit_logs', 'model_switch_audit', 'tool_audit_logs'],
    keyInteractions: ['Filter by actor', 'Filter by resource', 'Export CSV/JSON'],
  },
  {
    slug: 'settings',
    title: 'System Settings',
    description: 'Global control-plane, auth, tenant governance, and observability settings.',
    pageLayout: 'Settings sections grouped by security, runtime, AI, and observability.',
    components: ['MetricsCards'],
    apiEndpoints: ['/admin/system'],
    databaseEntities: ['system_settings', 'tenant_policies', 'api_keys', 'feature_flags'],
    keyInteractions: ['Review global defaults', 'Inspect security posture', 'Plan rollout changes'],
  },
];
